micronaut:
  application:
    name: broken-micronaut-openapi-expand
  server:
    context-path: /api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    token:
      propagation:
        enabled: true
      jwt:
        signatures:
          jwks:
            authzserver:
              url: ${authzserver.url}/oauth2/jwks
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()

authzserver.url: ${AUTHZSERVER_URL}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update

datasources:
  default:
    driver-class-name: org.h2.Driver
    dialect: H2
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa

